activePluginPack: PoE
generalActivationKey: f7
pluginConfig:
  Autoloot:
    chests:
      blight: '1'
      breach: '0'
      expedition: '0'
      heist: '0'
      legion: '0'
    hotkey: f3
  Autopress:
    clickOnPause:
      activated: 1
      delay: 1200
    hotkey: q
    keys:
    - key: a
      key_delay: 0
    - key: t
      key_delay: 17000
    - key: z
      key_delay: 0
    - key: e
      key_delay: 0
  BulkItemClicker:
    mode1Hotkey: f2
    mode2Hotkey: maj+f2
  InventoryEmptyer:
    hotkey: f4
    inventoryPosition:
      bottomCorner:
        x: 2534
        y: 1127
      topCorner:
        x: 1979
        y: 790
pluginPacks:
  PoE:
  - Autoloot
  - Bulk Item Clicker
  - Inventory Emptyer
  - Autopress
