activePluginPack: PoE
generalActivationKey: f7
pluginConfig:
  Autoloot:
    hotkey: f3
  Autopress:
    clickOnPause:
      activated: 1
      delay: 1200
    hotkey: q
    keys:
    - key: a
      key_delay: 0
    - key: z
      key_delay: 0
  BulkItemClicker:
    mode1Hotkey: f2
    mode2Hotkey: maj+f2
  InventoryEmptyer:
    hotkey: f4
    inventoryPosition:
      bottomCorner:
        x: 2544
        y: 1138
      topCorner:
        x: 1836
        y: 777
pluginPacks:
  PoE:
  - Autoloot
  - Bulk Item Clicker
  - Inventory Emptyer
  - Autopress
